### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by StarClutch** [smartlook/smartlook-android-sdk#1]
Version: 0.9.0.1.2.7-beta
b line 427
com.smartlook.sdk.smartlook.a.c.c.b.b

Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.presentr.android/com.presentr.android.ui.Login.LoginLoadingActivity}: java.util.ConcurrentModificationException
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2927)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2988)
       at android.app.ActivityThread.-wrap14(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1631)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6682)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

Caused by java.util.ConcurrentModificationException
       at java.util.ArrayList$Itr.next(ArrayList.java:831)
       at com.smartlook.sdk.smartlook.a.c.c.b.b(SourceFile:427)
       at com.smartlook.sdk.smartlook.a.c.c.b.a(SourceFile:383)
       at com.smartlook.sdk.smartlook.a.c.c.b.a(SourceFile:119)
       at com.smartlook.sdk.smartlook.a.c.a$2.onActivityStarted(SourceFile:106)
       at android.app.Application.dispatchActivityStarted(Application.java:231)
       at android.app.Activity.onStart(Activity.java:1270)
       at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:552)
       at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1256)
       at android.app.Activity.performStart(Activity.java:6959)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2890)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2988)
       at android.app.ActivityThread.-wrap14(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1631)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6682)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

**Comment by adamblack** [comment]
Hi @StarClutch ,

thank you for the report.

This issue should be fixed in new version: 0.9.0.1.4.2-beta
