### ISSUE TITLE
Crash when destroy Activity

### ISSUE THREAD

**Issue by Yunfeng1u** [smartlook/smartlook-android-sdk#11]
```
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewTreeObserver android.view.View.getViewTreeObserver()' on a null object reference
                                                                                    at com.smartlook.sdk.smartlook.analytics.c.a.a.a(SourceFile:78)
                                                                                    at com.smartlook.sdk.smartlook.analytics.c.b$1.onActivityDestroyed(SourceFile:110)
                                                                                    at android.app.Application.dispatchActivityDestroyed(Application.java:253)
                                                                                    at android.app.Activity.onDestroy(Activity.java:1846)
                                                                                    at android.support.v4.app.FragmentActivity.onDestroy(FragmentActivity.java:358)
                                                                                    at android.support.v7.app.AppCompatActivity.onDestroy(AppCompatActivity.java:209)
```

**Comment by Yunfeng1u** [comment]
I remove all the views in the Activity, which causes this crash.
