### ISSUE TITLE
Smartlook makes the app crashes

### ISSUE THREAD

**Issue by cmarrero01** [smartlook/smartlook-android-sdk#14]
We implement Smartlook in our new version of our Mobile App, and the Smartlook SDK makes the app crash randomly, the fabric cash log says this:

Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.app.mercury/com.app.mercury.conversational.activities.ArchivedProspectsActivity}: java.util.ConcurrentModificationException
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2955)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3030)
       at android.app.ActivityThread.-wrap11(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6938)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

Caused by java.util.ConcurrentModificationException
       at java.util.ArrayList$Itr.next(ArrayList.java:860)
       at com.smartlook.sdk.smartlook.analytics.c.e.a.b(SourceFile:398)
       at com.smartlook.sdk.smartlook.analytics.c.e.a.a(SourceFile:354)
       at com.smartlook.sdk.smartlook.analytics.c.e.a.a(SourceFile:121)
       at com.smartlook.sdk.smartlook.analytics.c.b$1.onActivityStarted(SourceFile:84)
       at android.app.Application.dispatchActivityStarted(Application.java:231)
       at android.app.Activity.onStart(Activity.java:1296)
       at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:614)
       at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
       at com.sirena.mercury.views.activities.BaseActivity.onStart(BaseActivity.java:104)
       at com.app.mercury.conversational.activities.ArchivedProspectsActivity.onStart(ArchivedProspectsActivity.kt:76)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1340)
       at android.app.Activity.performStart(Activity.java:7200)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2918)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3030)
       at android.app.ActivityThread.-wrap11(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6938)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

We are still trying this software to get data from our users, if this goes well we will make an upgrade of this account, but if this still happend, we can\'t use smarlook for our product.

Best

**Comment by adamblack** [comment]
Hello @cmarrero01 ,

this issue is going to be fixed in new release, should be published soon. Will let you know once it is done. :]

**Comment by adamblack** [comment]
Hi @cmarrero01 ,

should be fixed in new version.
