### ISSUE TITLE
Crash in onAttachedToWindow

### ISSUE THREAD

**Issue by LukasVykuka** [smartlook/smartlook-android-sdk#15]
Crash occurs after `onActivityResult` is called.

SDK version 0.9.0.2.1.4-beta

```
java.lang.NullPointerException: Attempt to invoke interface method 'void android.view.Window$Callback.onAttachedToWindow()' on a null object reference
        at com.smartlook.sdk.smartlook.analytics.c.d.b.a.onAttachedToWindow(SourceFile:103)
        at com.android.internal.policy.DecorView.onAttachedToWindow(DecorView.java:1433)
        at android.view.View.dispatchAttachedToWindow(View.java:15407)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2956)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1528)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1258)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6348)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
        at android.view.Choreographer.doCallbacks(Choreographer.java:683)
        at android.view.Choreographer.doFrame(Choreographer.java:619)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6123)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
```

**Comment by SenNeonoveNoci** [comment]
Hi @LukasVykuka

we gonna look into your issue and keep you informed. 

Can you provide us with more info? 
- Is this crash occurring on all Android versions?
- Is it device specific?
- And what version of SDK are you using?

**Comment by LukasVykuka** [comment]
It's happen on all devices and all Android versions.
SDK version 0.9.0.2.1.4-beta

**Comment by LukasVykuka** [comment]
I have another info: it happen if `onActivityResult` is called in Activity which have `SurfaceView` in layout for playing video. Crashing even with Smartlook.init(key, false).

**Comment by Acro** [comment]
@LukasVykuka The fix is underway and should be part of next release. We will update this issue accordingly.

**Comment by Acro** [comment]
@LukasVykuka The release is planned for today.

**Comment by adamblack** [comment]
Hi @LukasVykuka ,

should be fixed in new version.

**Comment by LukasVykuka** [comment]
I confirm, thanks.
