### ISSUE TITLE
Crashes with OkHttp 4.x

### ISSUE THREAD

**Issue by Pitel** [smartlook/smartlook-android-sdk#20]
Have OkHttp 4.x dependency in your app, and the app crashes.

```
2019-07-17 11:10:04.114 4062-4233 E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
    Process: cz.masterapp.annie2, PID: 4062
    java.lang.NoSuchMethodError: No static method hasBody(Lokhttp3/Response;)Z in class Lokhttp3/internal/http/HttpHeaders; or its super classes (declaration of 'okhttp3.internal.http.HttpHeaders' appears in /data/app/cz.masterapp.annie2-jwqUSkkBYqmRFTT6UhiueQ==/base.apk!classes18.dex)
        at com.smartlook.sdk.smartlook.b.g$a.b(SourceFile:517)
        at com.smartlook.sdk.smartlook.b.g$a.a(SourceFile:511)
        at com.smartlook.sdk.smartlook.b.g$a.intercept(SourceFile:450)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at com.smartlook.sdk.smartlook.a.a.c$1.intercept(SourceFile:191)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:37)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:71)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:184)
        at okhttp3.RealCall$AsyncCall.run(RealCall.kt:136)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
```

Similiar issue is here: jgilfelt/chuck#90 and solved here: ChuckerTeam/chucker#53

**Comment by SenNeonoveNoci** [comment]
Hi @Pitel,

please try to use `com.smartlook.recording:app:1.0.0-okhttp-fix`. We hopefully fixed the `okhttp` version incompatibility problem. 

Note that this is a pre-release version of SDK that uses new API. Documentation can be found [here](https://github.com/smartlook/smartlook.github.io/blob/0ee9c1b9ff658824d0e9b8b4a07e9cea612bc9f0/_docs/sdk/android.md). But old should work just fine as well (gonna be marked as deprecated).

**Comment by Pitel** [comment]
Yup, it's fixed in this pre-release version :+1:
