### ISSUE TITLE
LeakCanary menu crash

### ISSUE THREAD

**Issue by Pitel** [smartlook/smartlook-android-sdk#21]
Using version 1.0.0 of your SDK

We have [LeakCanary 2.0](https://square.github.io/leakcanary) in our app, and sometimes (not always), when we click on the menu in LeakCanary's activity, the app crashes in your code.

```
2019-07-19 16:20:59.296 29270-29270 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: cz.masterapp.annie2, PID: 29270
    java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter menu
        at com.smartlook.sdk.smartlook.analytics.c.g.b.a.onMenuOpened(Unknown Source:2)
        at com.android.internal.policy.PhoneWindow$ActionMenuPresenterCallback.onOpenSubMenu(PhoneWindow.java:2276)
        at com.android.internal.view.menu.BaseMenuPresenter.onSubMenuSelected(BaseMenuPresenter.java:211)
        at android.widget.ActionMenuPresenter.showOverflowMenu(ActionMenuPresenter.java:558)
        at android.widget.ActionMenuPresenter$OverflowMenuButton.performClick(ActionMenuPresenter.java:887)
        at android.view.View$PerformClick.run(View.java:24770)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by SenNeonoveNoci** [comment]
@Pitel 

This one is tricky. The SDK crashes on this `Window.Callback` callback method:

```
public abstract boolean onMenuOpened (int featureId, Menu menu)
```

The [documentation](https://developer.android.com/reference/android/view/Window.Callback.html#onMenuOpened(int,%2520android.view.Menu)) for this method says:

```
Menu: The menu that is opened. This value must never be null.
```

But LeakCanary 2.0 is apparently setting it to null. Our SDK is in correlation with official documentation. Not sure if we should fix this "error".

We are going to discous it internally and will let you know.

**Comment by SenNeonoveNoci** [comment]
Ok, we gonna fix it. look forward to next minor release.

**Comment by Pitel** [comment]
Well, it's FOSS, you can see their code [here](https://github.com/square/leakcanary/tree/master/leakcanary-android-core/src/main/java/leakcanary/internal) (in the `activity` and `navigation`) packages.

On first sight, I didn't noticed anything unusual, except they are generating the menu in code, using some Kotlin lambdas.
