### ISSUE TITLE
App crashes randomly - 1.0.0-native build

### ISSUE THREAD

**Issue by Maf-Dy** [smartlook/smartlook-android-sdk#22]
Java project running on Samsung Tab A 10 inch tablet that is running android Pie API 28
i am running into this problem each time i start my app

java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter rid
        at com.smartlook.sdk.smartlook.a.a.d$e.<init>(Unknown Source:12)
        at com.smartlook.sdk.smartlook.a.a.d.a(SourceFile:292)
        at com.smartlook.sdk.smartlook.a.a.d.a(SourceFile:230)
        at com.smartlook.sdk.smartlook.analytics.b.c(SourceFile:186)
        at com.smartlook.sdk.smartlook.analytics.b.b(SourceFile:168)
        at com.smartlook.sdk.smartlook.analytics.b.i(SourceFile:129)
        at com.smartlook.sdk.smartlook.analytics.b.a(SourceFile:42)
        at com.smartlook.sdk.smartlook.analytics.a.b(SourceFile:68)
        at com.smartlook.sdk.smartlook.analytics.a.b(SourceFile:61)
        at com.smartlook.sdk.smartlook.analytics.a.a(SourceFile:55)
        at com.smartlook.sdk.smartlook.a.a.d.b(SourceFile:95)
        at com.smartlook.sdk.smartlook.a.a.d.a(SourceFile:25)
        at com.smartlook.sdk.smartlook.a.a.d$l$a.run(SourceFile:69)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7072)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)

**Comment by Pitel** [comment]
#21 is also `method` NPE

**Comment by SenNeonoveNoci** [comment]
Hi @Maf-Dy,

I'm gonna look into this and keep you updated.

**Comment by SenNeonoveNoci** [comment]
@Maf-Dy This issue should be resolved in `com.smartlook.recording:app:1.0.1-native`.
