### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by kshivang** [smartlook/smartlook-android-sdk#37]
Android Version: 9
Device: Galaxy M30

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'org.json.JSONObject com.smartlook.sdk.smartlook.a.c.c.toJson()' on a null object reference
       at com.smartlook.sdk.smartlook.analytics.b.a(SourceFile:226)
       at com.smartlook.sdk.smartlook.analytics.a.a(SourceFile:115)
       at com.smartlook.sdk.smartlook.a.b.b.a(SourceFile:143)
       at com.smartlook.sdk.smartlook.a.b.b.a(SourceFile:16)
       at com.smartlook.sdk.smartlook.a.b.b$e.a(SourceFile:118)
       at com.smartlook.sdk.smartlook.a.b.b$e.a(SourceFile:112)
       at com.smartlook.sdk.smartlook.a.a.a(SourceFile:9)
       at com.smartlook.sdk.smartlook.a.a.a(SourceFile:5)
       at com.smartlook.sdk.smartlook.a.b$f.a(SourceFile:53)
       at com.smartlook.sdk.smartlook.a.a.a$b$c.run(SourceFile:306)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7156)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
```

**Comment by adamblack** [comment]
Hi @kshivang ,

thanks for report. Just to be sure, which version are you using?

**Comment by SanchoPanchos** [comment]
@adamblack same issue, using 1.2.0-native

**Comment by kshivang** [comment]
Hey @adamblack 

Sorry for late response, using 1.2.0-native

**Comment by SenNeonoveNoci** [comment]
Please try to use the latest version of SDK. It should be all fixed there.
